pekko.http.server.preview.enable-http2 = on

broker {
  ip = "127.0.0.1"
  ip = ${?BROKER_IP}

  port = 8080
  port = ${?BROKER_PORT}

  actors = 8
  actors = ${?BROKER_ACTORS}

  mode = "high-throughput"
  mode = ${?BROKER_STORAGE_MODE}

  max-messages-per-channel = 10000
  max-messages-per-channel = ${?MAX_MESSAGES}

  overflowPolicy = "drop-oldest"

  producer {
    timeout = 2 seconds
    timeout = ${?PRODUCER_TIMEOUT}
    parallelism = 16 # optional
  }
}

pekko {
  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]

  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
}